name: Build Release

# This workflow is triggered manually
on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest} #, windows-latest, macos-latest]
        python-version: [3.10.5]
        include:
          - os: ubuntu-latest
            release-name: Linux
          #- os: windows-latest
          #  release-name: Windows
          #- os: macos-latest
          #  release-name: MacOS

    # Use bash shell for all steps
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches, required for versioning
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build release
        run: |
          python setup.py build
      - name: Get latest release tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          # name example: "PhantomDesktop-Windows-v1.0.0.zip", "PhantomDesktop-Linux-v2.5.1.zip"
          name: PhantomDesktop-${{ matrix.release-name }}-${{ steps.previoustag.outputs.tag }}.zip
          path: ./build/
      